### ISSUE TITLE
The project doesn't start

### ISSUE THREAD

**Issue by igor-adzz** [brovan-rus/todo_list_test_task#1]
I've tried to run the project following the instructions in README file, but I've got some errors:
![image](https://github.com/brovan-rus/todo_list_test_task/assets/127742125/7ecf5d35-0edf-44c8-960a-50a57c59c9cb)

**Comment by brovan-rus** [comment]
I made fixes in Readme file, you have to install dependencies, before start project with command ```npm install``` from backend and frontend folders.
